---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - webapp.dev.rishabagarwal.me
  resources:
  - operators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.dev.rishabagarwal.me
  resources:
  - operators/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.dev.rishabagarwal.me
  resources:
  - operators/status
  verbs:
  - get
  - patch
  - update
